# Generated by Django 5.2 on 2025-04-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Название события',
                'verbose_name_plural': 'Названия событий',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание сбора')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма сбора')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Обложка сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сбора')),
                ('end_time', models.DateTimeField(verbose_name='Дата завершения сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('event', models.ManyToManyField(to='collect.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
                'default_related_name': 'collects',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время совершения платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.collect', verbose_name='Сбор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'default_related_name': 'payments',
            },
        ),
    ]
